### ISSUE TITLE
Flow API related todo list

### ISSUE THREAD

**Issue by platosha** [vaadin/vaadin-radio-button#25]
### Value compatibility

Make sure all public-available user input elements follow these rules:

- [ ] the `value` property is declared as `String`
- [ ] the `value` property is not read-only and allows changes
- [ ] the `value` property declaration has `notify: true`

### Validation compatibility

Make sure all public-available validatable elements follow these rules:

- [ ] the `invalid` property is declared as `Boolean`
- [ ] the `invalid` property has `notify: true`
- [ ] `validate()` method updates the `invalid` state property

**Comment by jouni** [comment]
@platosha, this seems like it has been left hanging while all of the other related issues have been fixed/closed.

**Comment by platosha** [comment]
I think there is nothing to fix here, everything is good.

- The `value` property of `<vaadin-radio-button>` does not have `notify: true`. Makes sense this way, because `<vaadin-radio-button>` never changes its `value`.
- The `value` property of `<vaadin-radio-group>` does change, and is `String` with `notify: true`, so it’s good.
- We don’t have validation feature in this component yet, so the validation compatibility requirements do not apply.
